/* @flow */

export default [
  {
    location: 'Arizona',
    name: 'Cardinals',
    website: 'azcardinals.com',
    code: 'ARI',
    division: 'NFC West',
  },
  {
    location: 'Atlanta',
    name: 'Falcons',
    website: 'atlantafalcons.com',
    code: 'ATL',
    division: 'NFC South',
  },
  {
    location: 'Baltimore',
    name: ' Ravens',
    website: 'baltimoreravens.com',
    code: 'BAL',
    division: 'AFC North',
  },
  {
    location: 'Buffalo',
    name: 'Bills',
    website: 'buffalobills.com',
    code: 'BUF',
    division: 'AFC East',
  },
  {
    location: 'Carolina',
    name: 'Panthers',
    website: 'panthers.com',
    code: 'CAR',
    division: 'NFC South',
  },
  {
    location: 'Chicago',
    name: 'Bears',
    website: 'chicagobears.com',
    code: 'CHI',
    division: 'NFC North',
  },
  {
    location: 'Cincinnati',
    name: 'Bengals',
    website: 'bengals.com',
    code: 'CIN',
    division: 'AFC North',
  },
  {
    location: 'Cleveland',
    name: 'Browns',
    website: 'clevelandbrowns.com',
    code: 'CLE',
    division: 'AFC North',
  },
  {
    location: 'Dallas',
    name: 'Cowboys',
    website: 'dallascowboys.com',
    code: 'DAL',
    division: 'NFC East',
  },
  {
    location: 'Denver',
    name: 'Broncos',
    website: 'denverbroncos.com',
    code: 'DEN',
    division: 'AFC West',
  },
  {
    location: 'Detroit',
    name: 'Lions',
    website: 'detroitlions.com',
    code: 'DET',
    division: 'NFC North',
  },
  {
    location: 'Green Bay',
    name: 'Packers',
    website: 'packers.com',
    code: 'GB',
    division: 'NFC North',
  },
  {
    location: 'Houston',
    name: 'Texans',
    website: 'houstontexans.com',
    code: 'HOU',
    division: 'AFC South',
  },
  {
    location: 'Indianapolis',
    name: 'Colts',
    website: 'colts.com',
    code: 'IND',
    division: 'AFC South',
  },
  {
    location: 'Jacksonville',
    name: 'Jaguars',
    website: 'jaguars.com',
    code: 'JAX',
    codeAlt: 'JAC',
    division: 'AFC South',
  },
  {
    location: 'Kansas City',
    name: 'Chiefs',
    website: 'chiefs.com',
    code: 'KC',
    division: 'AFC West',
  },
  {
    location: 'Los Angeles',
    name: 'Chargers',
    website: 'chargers.com',
    code: 'LAC',
    division: 'AFC West',
  },
  {
    location: 'Los Angeles',
    name: 'Rams',
    website: 'therams.com',
    code: 'LA',
    division: 'NFC West',
  },
  {
    location: 'Miami',
    name: 'Dolphins',
    website: 'miamidolphins.com',
    code: 'MIA',
    division: 'AFC East',
  },
  {
    location: 'Minnesota',
    name: 'Vikings',
    website: 'vikings.com',
    code: 'MIN',
    division: 'NFC North',
  },
  {
    location: 'New England',
    name: 'Patriots',
    website: 'patriots.com',
    code: 'NE',
    division: 'AFC East',
  },
  {
    location: 'New Orleans',
    name: 'Saints',
    website: 'neworleanssaints.com',
    code: 'NO',
    division: 'NFC South',
  },
  {
    location: 'New York',
    name: 'Giants',
    website: 'giants.com',
    code: 'NYG',
    division: 'NFC East',
  },
  {
    location: 'New York',
    name: 'Jets',
    website: 'newyorkjets.com',
    code: 'NYJ',
    division: 'AFC East',
  },
  {
    location: 'Oakland',
    name: 'Raiders',
    website: 'raiders.com',
    code: 'OAK',
    division: 'AFC West',
  },
  {
    location: 'Philadelphia',
    name: 'Eagles',
    website: 'philadelphiaeagles.com',
    code: 'PHI',
    division: 'NFC East',
  },
  {
    location: 'Pittsburgh',
    name: 'Steelers',
    website: 'steelers.com',
    code: 'PIT',
    division: 'AFC North',
  },
  {
    location: 'San Francisco',
    name: '49ers',
    website: '49ers.com',
    code: 'SF',
    division: 'NFC West',
  },
  {
    location: 'Seattle',
    name: 'Seahawks',
    website: 'seahawks.com',
    code: 'SEA',
    division: 'NFC West',
  },
  {
    location: 'Tampa Bay',
    name: 'Buccaneers',
    website: 'buccaneers.com',
    code: 'TB',
    division: 'NFC South',
  },
  {
    location: 'Tennessee',
    name: 'Titans',
    website: 'titansonline.com',
    code: 'TEN',
    division: 'AFC South',
  },
  {
    location: 'Washington',
    name: 'Redskins',
    website: 'redskins.com',
    code: 'WAS',
    division: 'NFC East',
  },
];
