/* @flow */

export default [
  {
    name: 'Arizona s',
    website: 'azcardinals.com',
    code: 'ARI',
    division: 'NFC West',
  },
  {
    name: 'Atlanta Falcons',
    website: 'atlantafalcons.com',
    code: 'ATL',
    division: 'NFC South',
  },
  {
    name: ' Ravens',
    website: 'baltimoreravens.com',
    code: 'BAL',
    division: 'AFC North',
  },
  {
    name: 'Buffalo Bills',
    website: 'buffalobills.com',
    code: 'BUF',
    division: 'AFC East',
  },
  {
    name: 'Carolina Panthers',
    website: 'panthers.com',
    code: 'CAR',
    division: 'NFC South',
  },
  {
    name: 'Chicago Bears',
    website: 'chicagobears.com',
    code: 'CHI',
    division: 'NFC North',
  },
  {
    name: 'Cincinnati Bengals',
    website: 'bengals.com',
    code: 'CIN',
    division: 'AFC North',
  },
  {
    name: 'Cleveland Browns',
    website: 'clevelandbrowns.com',
    code: 'CLE',
    division: 'AFC North',
  },
  {
    name: 'Dallas Cowboys',
    website: 'dallascowboys.com',
    code: 'DAL',
    division: 'NFC East',
  },
  {
    name: 'Denver Broncos',
    website: 'denverbroncos.com',
    code: 'DEN',
    division: 'AFC West',
  },
  {
    name: 'Detroit Lions',
    website: 'detroitlions.com',
    code: 'DET',
    division: 'NFC North',
  },
  {
    name: 'Green Bay Packers',
    website: 'packers.com',
    code: 'GB',
    division: 'NFC North',
  },
  {
    name: 'Houston Texans',
    website: 'houstontexans.com',
    code: 'HOU',
    division: 'AFC South',
  },
  {
    name: 'Indianapolis Colts',
    website: 'colts.com',
    code: 'IND',
    division: 'AFC South',
  },
  {
    name: 'Jacksonville Jaguars',
    website: 'jaguars.com',
    code: 'JAX',
    codeAlt: 'JAC',
    division: 'AFC South',
  },
  {
    name: 'Kansas City Chiefs',
    website: 'chiefs.com',
    code: 'KC',
    division: 'AFC West',
  },
  {
    name: 'Los Angeles Chargers',
    website: 'chargers.com',
    code: 'LAC',
    division: 'AFC West',
  },
  {
    name: 'Los Angeles Rams',
    website: 'therams.com',
    code: 'LA',
    division: 'NFC West',
  },
  {
    name: 'Miami Dolphins',
    website: 'miamidolphins.com',
    code: 'MIA',
    division: 'AFC East',
  },
  {
    name: 'Minnesota Vikings',
    website: 'vikings.com',
    code: 'MIN',
    division: 'NFC North',
  },
  {
    name: 'New England Patriots',
    website: 'patriots.com',
    code: 'NE',
    division: 'AFC East',
  },
  {
    name: 'New Orleans Saints',
    website: 'neworleanssaints.com',
    code: 'NO',
    division: 'NFC South',
  },
  {
    name: 'New York Giants',
    website: 'giants.com',
    code: 'NYG',
    division: 'NFC East',
  },
  {
    name: 'New York Jets',
    website: 'newyorkjets.com',
    code: 'NYJ',
    division: 'AFC East',
  },
  {
    name: 'Oakland Raiders',
    website: 'raiders.com',
    code: 'OAK',
    division: 'AFC West',
  },
  {
    name: 'Philadelphia Eagles',
    website: 'philadelphiaeagles.com',
    code: 'PHI',
    division: 'NFC East',
  },
  {
    name: 'Pittsburgh Steelers',
    website: 'steelers.com',
    code: 'PIT',
    division: 'AFC North',
  },
  {
    name: 'San Francisco 49ers',
    website: '49ers.com',
    code: 'SF',
    division: 'NFC West',
  },
  {
    name: 'Seattle Seahawks',
    website: 'seahawks.com',
    code: 'SEA',
    division: 'NFC West',
  },
  {
    name: 'Tampa Bay Buccaneers',
    website: 'buccaneers.com',
    code: 'TB',
    division: 'NFC South',
  },
  {
    name: 'Tennessee Titans',
    website: 'titansonline.com',
    code: 'TEN',
    division: 'AFC South',
  },
  {
    name: 'Washington Redskins',
    website: 'redskins.com',
    code: 'WAS',
    division: 'NFC East',
  },
];
